"""create final orders schema

Revision ID: 6b5282d48703
Revises:
Create Date: 2026-09-30 12:49:13.109411

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6b5282d48703"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "final_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_final_orders_status"),
        "final_orders",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_final_orders_user_id"),
        "final_orders",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "final_order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "unit_price", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["final_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_final_order_items_order_id"),
        "final_order_items",
        ["order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_final_order_items_order_id"), table_name="final_order_items"
    )
    op.drop_table("final_order_items")
    op.drop_index(op.f("ix_final_orders_user_id"), table_name="final_orders")
    op.drop_index(op.f("ix_final_orders_status"), table_name="final_orders")
    op.drop_table("final_orders")
    op.drop_table("users")
    # ### end Alembic commands ###
