syntax = "proto3";

package orders;

service OrdersService {
  rpc CreateOrder(CreateOrderRequest) returns (OrderResponse);
  rpc GetOrder(GetOrderRequest) returns (OrderResponse);
}

message OrderItem {
  string product_name = 1;
  int32 quantity = 2;
  double unit_price = 3;
}

message CreateOrderRequest {
  int32 customer_id = 1;
  repeated OrderItem items = 2;
}

message GetOrderRequest {
  int32 order_id = 1;
}

message OrderResponse {
  int32 order_id = 1;
  int32 customer_id = 2;
  string status = 3;
  double total = 4;
}